[package]
name = "assembler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
spdlog-rs = {version = "0.4.3", features = ["release-level-warn"]}
